//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFinanciero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.OrdenProduccions = new HashSet<OrdenProduccion>();
            this.ProyeccionGastos = new HashSet<ProyeccionGasto>();
            this.ProyeccionVentas = new HashSet<ProyeccionVenta>();
            this.RegistroGastos = new HashSet<RegistroGasto>();
            this.RegistroVentas = new HashSet<RegistroVenta>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string MedioEnvio { get; set; }
        public string EntidadSolicitante { get; set; }
        public string Justificacion { get; set; }
        public string Correo { get; set; }
        public int TipoSolicitud_id { get; set; }
        public int TipoMoneda_id { get; set; }
        public int TipoRegistro_id { get; set; }
    
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoReflejar TipoReflejar { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProduccion> OrdenProduccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyeccionGasto> ProyeccionGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyeccionVenta> ProyeccionVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroGasto> RegistroGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroVenta> RegistroVentas { get; set; }
    }
}
