//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFinanciero.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFEntities : DbContext
    {
        public SFEntities()
            : base("name=SFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuentaContable> CuentaContables { get; set; }
        public virtual DbSet<OrdenProduccion> OrdenProduccions { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<ProyeccionGasto> ProyeccionGastos { get; set; }
        public virtual DbSet<ProyeccionVenta> ProyeccionVentas { get; set; }
        public virtual DbSet<RegistroGasto> RegistroGastos { get; set; }
        public virtual DbSet<RegistroVenta> RegistroVentas { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<TipoMoneda> TipoMonedas { get; set; }
        public virtual DbSet<TipoReflejar> TipoReflejars { get; set; }
        public virtual DbSet<TipoSolicitud> TipoSolicituds { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
