//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFinanciero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProduccion
    {
        public int id { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public string estado { get; set; }
        public int cuenta_contable_id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
    }
}
