//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFinanciero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyeccionVenta
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto_proyectado { get; set; }
        public string producto { get; set; }
        public int cuenta_contable_id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
    }
}
